services:
  # Base de Datos PostgreSQL
  turing_db_v2:
    image: postgres:15-alpine
    container_name: turing_project_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sistema_academico_db
    ports:
      - '5436:5432'
    volumes:
      - turing_postgres_data:/var/lib/postgresql/data

  # PgAdmin (Interfaz visual para ver la BD)
  pgadmin:
    image: dpage/pgadmin4
    container_name: turing_project_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5051:80'
    depends_on:
      - turing_db_v2

volumes:
  turing_postgres_data:
